name: build wine
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - wine/**
permissions:
  packages: write

jobs:
  push:
    name: "yolks:wine_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 7
          - 8
          - 9
          - 10
          - latest
          - devel
          - staging
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./wine
          file: ./wine/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/team-wurstwasser/yolks:wine_${{ matrix.tag }}
